<html xmlns="http://www.w3.org/1999/xhtml" xmlns:sa="http://www.elsevier.com/xml/common/struct-aff/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:prism="http://prismstandard.org/namespaces/basic/2.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" xml:lang="en">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="initial-scale=1, user-scalable=no"/>
  <head>
    <script src="/Cache/JsCss/Core.js"></script>
    <link rel="stylesheet" type="text/css" href="/Cache/JsCss/Core.css" media="all"/>
    <link id="favicon" rel="shortcut icon" type="image/png" href="/Lib/Img/cornerstone_80x80.png" />
  </head>
  <body>
    <div id="mainView" class="article">
      <h1>[[title]]</h1>
      <div class="para">[[text]]</div>
    </div>
    <span id="saveThisNote">
    	<button type="button" id="saveThisNoteButton">Save</button>
    	<button type="button" id="saveThisNoteReturnButton">Save and return</button>
    </span>
    </body>
    </html>