<html xmlns="http://www.w3.org/1999/xhtml" xmlns:sa="http://www.elsevier.com/xml/common/struct-aff/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:prism="http://prismstandard.org/namespaces/basic/2.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" xml:lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="viewport" content="initial-scale=1, user-scalable=no"/>
<head>
	<script src="/Cache/JsCss/Core.js"></script>
    <link rel="stylesheet" type="text/css" href="/Cache/JsCss/Css.css" media="all"/>
    <link id="favicon" rel="shortcut icon" type="image/png" href="/Lib/Img/cornerstone_80x80.png" />
</head>
<body>

<div id="creditWindow">
    <div>You don't own enough credits, please select the amount of credits you want to puchase.</div>
    <div class="creditSelection">10 credits ($40)</div>
    <div class="creditSelection">20 credits ($75)</div>
    <div class="creditSelection">50 credits ($180)</div>

	<div style="font-size:10px;">
    	Here you can have some text about some terms and conditions, redirection to the store and bladiebla
    </div>

</div>



</body>
</html>